vercel deploy 오류
src/components/shop/ShopView.tsx(72,40): error TS2345: Argument of type 'CharacterType' is not assignable to parameter of type '"cat" | "fox"'.
  Type '"panda"' is not assignable to type '"cat" | "fox"'.
src/data/items.ts(293,88): error TS2367: This comparison appears to be unintentional because the types '1' and '3' have no overlap.
src/data/items.ts(331,88): error TS2367: This comparison appears to be unintentional because the types '1' and '3' have no overlap.
Error: Command "npm run build" exited with 2